models:
  - type: main
    engine: openai
    model: meta/llama-3.1-8b-instruct
    parameters:
      base_url: "http://nim-llm.nim.svc.cluster.local:8000/v1"
      api_key: "not-needed"

colang_version: "1.0"

rails:
  input:
    flows:
      - check prompt injection
      - check pii in input
      - check topical
